project_name: tfcheck
env:
- GO111MODULE=on
before:
  hooks:
  - go mod download
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ldflags:
  - -s -w
  - -X main.AppName={{.ProjectName}}
  - -X main.Version={{.Version}}
  - -X main.Revision={{.ShortCommit}}
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
release:
  prerelease: auto
